global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  - url: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push
    basic_auth:
      username: 3308244
      password: YOUR_GRAFANA_API_KEY

scrape_configs:
  - job_name: "aegisflow"

    static_configs:
      - targets: ["localhost:8080"]
        labels:
          app: "aegisflow"

  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"
