apiVersion: apps/v1
kind: Deployment

metadata:
  name: aegisflow-gateway

spec:
  replicas: 2   #initially starting with 2 Gateway pods, in case 1 dies

  selector:     #gateway finds pods on it's own by using labels
    matchLabels:  
      app.kubernetes.io/name: aegisflow
      app.kubernetes.io/component: gateway

  template:     #blueprint of every pod, kubernetes copies this when recreates another pod
    metadata:
      labels:
        app.kubernetes.io/name: aegisflow
        app.kubernetes.io/component: gateway
        app.kubernetes.io/part-of: aegisflow-platform

    spec:
      containers:
        - name: gateway

          image: aegisflow-api:latest

          imagePullPolicy: Never

          ports:
            - containerPort: 8080
          
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080

            initialDelaySeconds: 5    #wait 5s before checking
            periodSeconds: 5          #check every 5s
            timeoutSeconds: 2         #if ready doesnt answer in 2 sec, consider probe failed
            failureThreshold: 3       #need 3 consecutive failures before marking not ready

          livenessProbe:
            httpGet:
              path: /live
              port: 8080

            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          startupProbe:
            httpGet:
              path: /live
              port: 8080

            periodSeconds: 5

            failureThreshold: 12

            timeoutSeconds: 2

          env:
            - name: PORT
              value: "8080"

            - name: REDIS_HOST
              value: "redis"

            - name: REDIS_PORT
              value: "6379"

          resources:    #cost optimization, tell cpu how much storage this gateway needs 
            requests:
              cpu: "250m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"